apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: wondrous-rohan-hc
  namespace: apps-release
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 7070
        requestPath: /docs  # Change this to a path that returns 200 OK
  targetRef:
    group: ""
    kind: Service
    name: wondrous-rohan-dc7f631b7f-srv
