kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: wondrous-rohan-dc7f631b7f-scaler
  namespace: apps-release
spec:
  hosts:
    - cc1fbde45ead-in-south-01.mayson.dev
  pathPrefixes:
    - /us-west-1-backstractelb-eaea2f-coll-40b587e0e76f464c8cb78a581d06c1c5/ # e.g. /infallible-naveen-... wondrous-rohan-dc7f631b7f/
  scaleTargetRef:
    name: wondrous-rohan-dc7f631b7f-depl
    kind: Deployment
    apiVersion: apps/v1
    service: wondrous-rohan-dc7f631b7f-srv # e.g. coll-8a2a...-srv
    port: 80
  replicas:
    min: 0
    max: 10
  scaledownPeriod: 1800 #inseconds
  scalingMetric:
    requestRate:
      targetValue: 100
      window: 1m
